language: go

go:
  - 1.11
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -b /bin

script:
  - golangci-lint run
  - go test -v -race ./...

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.11" && goveralls -service=travis-ci